### ISSUE TITLE
Not mobile friendly

### ISSUE THREAD

**Issue by CarsonBurke** [delivey/tapke#1]
Very cool project! Please add like 2 media queries so I can speedrun it on my phone 😀

**Comment by delivey** [comment]
Hey, fixed styling and it should look good on mobile after I push.

The issue is this: https://stackoverflow.com/questions/22473950/keypress-event-not-firing-in-android-mobile.
Chrome doesn't want to cooperate with me and returns 229 for every `onKeyDown` event. I think the only way to fix this is to write a new input-based and use some trick to hide the input. I'll let you know if I make any progress.
